"""Required-$n$ lookup over the paper's certification tables.

The paper's certification table gives, per benchmark family and per declared
margin, the number of items an equivalence test needs at the 25th, 50th and 75th
percentile of the per-item disagreement rates the atlas observes for that
family. Reading it out of a PDF is exactly the friction this module removes:

    >>> from flipeval import required_n_for_benchmark
    >>> row = required_n_for_benchmark("mmlu", margin_pp=2.0)
    >>> row.required_n("median")
    2164

WHERE THE DATA COMES FROM. The rows are the released artifact
``results/certification_tables_rev2.csv``, generated by
``scripts/certification_tables.py`` from the rev-2 atlas. A byte-identical copy
ships inside the package as ``flipeval/data/certification_tables_rev2.csv`` so
that the lookup also works from an installed distribution, where ``results/`` is
not present. The two copies are pinned to each other by
``tests/test_certification_lookup.py``, which fails if either drifts: a second
copy of a released artifact is only safe while something checks it is the same
copy.

WHAT THE NUMBERS MEAN. Every ``required_n`` here is the standard TOST planning
sample size under an assumed **true** paired difference of zero, at one-sided
alpha = .05 and 80% power. It answers "how many items would this benchmark need
for an equivalence test to have 80% power, given how much models of this kind
disagree item by item". It does *not* answer "how many items would certify the
delta I observed"; under a true difference the requirement is larger and grows
without bound as the difference approaches the margin. These are design tables.

MARGINS ARE IN PERCENTAGE POINTS HERE. ``margin_pp=2.0`` is a two-point margin.
``flipeval.compare`` takes the same quantity as a proportion (``margin=0.02``)
because it is comparing it against accuracies. The two entry points are
deliberately not unified -- the table is published in points -- so both sides
range-check their argument and say which unit they wanted.
"""
from __future__ import annotations

import csv
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Sequence

from scipy import stats

#: The copy that ships with the package. Byte-identical to the released
#: ``results/certification_tables_rev2.csv``; see the module docstring.
PACKAGED_TABLE = Path(__file__).resolve().parent / "data" / "certification_tables_rev2.csv"

#: Row label of the pooled row, spelled as it appears in the released CSV.
POOLED = "ALL (pooled)"

ALPHA = 0.05
POWER = 0.80

PERCENTILES = ("p25", "median", "p75")

#: Spellings a caller may plausibly type for the pooled row.
_POOLED_ALIASES = frozenset({"all", "pooled", "all (pooled)", "all_pooled", "overall"})


@dataclass(frozen=True)
class RequiredN:
    """One (benchmark family, margin) row of the certification table."""

    benchmark_family: str
    margin_pp: float
    n_atlas_cells: int
    median_baseline_accuracy: float
    discordance_p25: float
    discordance_median: float
    discordance_p75: float
    required_n_p25: int
    required_n_median: int
    required_n_p75: int
    required_n_independent_binomial: int
    paired_advantage_at_median: float
    source: str

    def required_n(self, percentile: str = "median") -> int:
        """Items required at the given percentile of observed churn.

        ``percentile`` is one of ``p25`` (optimistic: this family's compressions
        usually churn less than this), ``median`` (typical) or ``p75``
        (pessimistic).
        """
        return int(getattr(self, f"required_n_{_check_percentile(percentile)}"))

    def discordance(self, percentile: str = "median") -> float:
        """The observed per-item disagreement rate the requirement was computed at."""
        return float(getattr(self, f"discordance_{_check_percentile(percentile)}"))

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _check_percentile(percentile: str) -> str:
    if percentile not in PERCENTILES:
        raise ValueError(
            f"percentile must be one of {', '.join(PERCENTILES)}; got {percentile!r}"
        )
    return percentile


def _normalize(name: str) -> str:
    collapsed = " ".join(str(name).strip().lower().split())
    if collapsed in _POOLED_ALIASES:
        return POOLED.lower()
    return collapsed.replace("-", "_")


def load_certification_table(table: str | Path | None = None) -> list[RequiredN]:
    """Read the certification table into :class:`RequiredN` rows.

    ``table`` defaults to the copy shipped with the package. Pass a path to read
    a different one -- for instance ``results/certification_tables_rev2.csv`` in
    a source checkout, or a regenerated table.
    """
    path = Path(table) if table is not None else PACKAGED_TABLE
    if not path.is_file():
        raise FileNotFoundError(
            f"certification table not found: {path}. "
            "Pass the path to a certification_tables CSV, or omit the argument to "
            f"use the copy shipped with flipeval ({PACKAGED_TABLE})."
        )
    with path.open("r", encoding="utf-8", newline="") as stream:
        rows = list(csv.DictReader(stream))
    if not rows:
        raise ValueError(f"{path} contains no rows")
    required_columns = {
        "benchmark_family",
        "margin_pp",
        "n_atlas_cells",
        "median_baseline_accuracy",
        "discordance_p25",
        "discordance_median",
        "discordance_p75",
        "required_n_p25",
        "required_n_median",
        "required_n_p75",
        "required_n_independent_binomial",
        "paired_advantage_at_median",
    }
    missing = sorted(required_columns - set(rows[0]))
    if missing:
        raise ValueError(
            f"{path} is not a certification table: missing column(s) {', '.join(missing)}. "
            "Expected the schema of results/certification_tables_rev2.csv."
        )
    source = str(path)
    return [
        RequiredN(
            benchmark_family=row["benchmark_family"],
            margin_pp=float(row["margin_pp"]),
            n_atlas_cells=int(row["n_atlas_cells"]),
            median_baseline_accuracy=float(row["median_baseline_accuracy"]),
            discordance_p25=float(row["discordance_p25"]),
            discordance_median=float(row["discordance_median"]),
            discordance_p75=float(row["discordance_p75"]),
            required_n_p25=int(row["required_n_p25"]),
            required_n_median=int(row["required_n_median"]),
            required_n_p75=int(row["required_n_p75"]),
            required_n_independent_binomial=int(row["required_n_independent_binomial"]),
            paired_advantage_at_median=float(row["paired_advantage_at_median"]),
            source=source,
        )
        for row in rows
    ]


def available_benchmarks(table: str | Path | None = None) -> list[str]:
    """Benchmark families present in the table, in file order."""
    seen: list[str] = []
    for row in load_certification_table(table):
        if row.benchmark_family not in seen:
            seen.append(row.benchmark_family)
    return seen


def available_margins_pp(table: str | Path | None = None) -> list[float]:
    """Margins (in percentage points) the table is computed at."""
    return sorted({row.margin_pp for row in load_certification_table(table)})


def required_n_for_benchmark(
    benchmark: str,
    margin_pp: float = 2.0,
    *,
    table: str | Path | None = None,
) -> RequiredN:
    """Look up the certification requirement for one family at one margin.

    ``margin_pp`` is in **percentage points** (2.0 = a two-point margin), which
    is how the published table is indexed.

    Raises ``ValueError`` naming what is available when the family or the margin
    is not in the table -- an off-table margin is refused rather than
    interpolated, because the published requirement is quadratic in the margin
    and a silently interpolated row would not be the paper's number.
    """
    rows = load_certification_table(table)
    wanted = _normalize(benchmark)
    matched = [row for row in rows if _normalize(row.benchmark_family) == wanted]
    if not matched:
        families = ", ".join(sorted({row.benchmark_family for row in rows}))
        raise ValueError(
            f"unknown benchmark family {benchmark!r}. "
            f"The certification table covers: {families}. "
            "Sub-task names are not mapped to families automatically (mmlu_pro is "
            "its own family, not a variant of mmlu), so pass the family name."
        )
    if not isinstance(margin_pp, (int, float)) or isinstance(margin_pp, bool):
        raise TypeError(f"margin_pp must be a number in percentage points; got {margin_pp!r}")
    if margin_pp <= 0:
        raise ValueError(f"margin_pp must be positive; got {margin_pp!r}")
    if margin_pp < 0.1:
        raise ValueError(
            f"margin_pp is in PERCENTAGE POINTS here; got {margin_pp!r}, which is "
            f"{margin_pp} points. A two-point margin is margin_pp=2.0, not 0.02 "
            "(flipeval.compare takes the same quantity as a proportion)."
        )
    for row in matched:
        if math.isclose(row.margin_pp, float(margin_pp), rel_tol=0.0, abs_tol=1e-9):
            return row
    margins = ", ".join(f"{value:g}" for value in sorted({row.margin_pp for row in matched}))
    raise ValueError(
        f"the certification table is computed at margins {margins} pp; got {margin_pp:g}. "
        "For an off-table margin, compute it from this family's observed churn with "
        "flipeval.certification.required_n_from_discordance(discordance, margin_pp); "
        "the table is not interpolated because the requirement is quadratic in the margin."
    )


def required_n_from_discordance(
    discordance: float,
    margin_pp: float,
    alpha: float = ALPHA,
    power: float = POWER,
) -> int:
    """Paired TOST planning sample size for a given per-item disagreement rate.

    The paper's Equation (2): with paired standard deviation
    ``sd = sqrt(p_d)`` and a true difference assumed to be zero,

        n = ceil( ((z_{1-alpha} + z_{1-beta}) * sd / m)^2 )

    at one-sided ``alpha``. This is the formula that produced every
    ``required_n`` column in the released table, and
    ``tests/test_certification_lookup.py`` recomputes all 108 of them through
    this function to keep the two from forking.

    ``margin_pp`` is in percentage points; ``discordance`` is a rate in [0, 1].
    """
    if not 0.0 <= discordance <= 1.0:
        raise ValueError(f"discordance is a rate in [0, 1]; got {discordance!r}")
    if margin_pp <= 0:
        raise ValueError(f"margin_pp must be positive; got {margin_pp!r}")
    if not 0 < alpha < 1:
        raise ValueError(f"alpha must be between zero and one; got {alpha!r}")
    if not 0 < power < 1:
        raise ValueError(f"power must be between zero and one; got {power!r}")
    if discordance == 0.0:
        return 1
    margin = float(margin_pp) / 100.0
    z = float(stats.norm.ppf(1 - alpha)) + float(stats.norm.ppf(power))
    return int(math.ceil((z * math.sqrt(discordance) / margin) ** 2))


def format_required_n(row: RequiredN, percentile: str = "median") -> str:
    """Human-readable block for one looked-up row, as the CLI prints it."""
    _check_percentile(percentile)
    lines: Sequence[str] = (
        f"{'benchmark family':<21}{row.benchmark_family}",
        f"{'margin':<21}+/-{row.margin_pp:g} pp",
        f"{'atlas cells':<21}{row.n_atlas_cells}",
        "",
        "Required n (paired TOST, one-sided alpha=0.05, 80% power, true difference zero)",
        f"  p25  churn {row.discordance_p25:.4f}   n {row.required_n_p25}",
        f"  med  churn {row.discordance_median:.4f}   n {row.required_n_median}",
        f"  p75  churn {row.discordance_p75:.4f}   n {row.required_n_p75}",
        "",
        f"{'selected (' + percentile + ')':<21}{row.required_n(percentile)} items",
        f"{'ignoring pairing':<21}{row.required_n_independent_binomial} items "
        f"({row.paired_advantage_at_median:g}x more at the median)",
        "",
        f"{'source':<21}{row.source}",
        "These are design tables: meeting the count makes the test informative, and",
        "the test still has to be run and to pass.",
    )
    return "\n".join(lines)
